services:
  - type: web
    name: work-report-app
    env: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    plan: free
    envVars:
      - key: PORT
        value: 3000
